### ISSUE TITLE
react-dom is not listed in peerDependencies

### ISSUE THREAD

**Issue by kirill-konshin** [tajo/react-portal#228]
react-dom is not listed in peerDependencies which causes Yarn 2 in plug'n'play mode to fail

**Comment by dasdachs** [comment]
@kirill-konshin Any solution for this?

**Comment by kirill-konshin** [comment]
@dasdachs add this to `.yarnrc.yml`:

```
packageExtensions:
  react-portal@*:
    peerDependencies:
      react-dom: "*"
```

@tajo is this project alive? Yarn 2 has been released long ago, please fix properly.
